{% set name = "ppmac" %}
{% set version = "0.1" %}
{% set sha256 = "766b8a579b0d56bbe68f0944780ec4a71ddbcdd859c963c565aaeee2d951dd94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-HXN/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - six
  run:
    - python
    - numpy >=1.8
    - paramiko

test:
  imports:
    - ppmac

about:
  home: https://github.com/NSLS-II-HXN/ppmac
  license: BSD
  license_file: LICENSE
  summary: Some Power PMAC Linux/Python tools
